/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs.cs2263.group4project;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void userInfoTests() {
        // Create new UserInfo
        UserInfo info = new UserInfo("shannon356", "Culley", "Shannon", "Business major", "shannon@isu.edu", "path", "password");

        // Test attemptLogin()
        // Test 1: Correct password
        assertTrue(info.attemptLogin("password"));
        // Test 2: Incorrect password
        assertFalse(info.attemptLogin("Password"));
        assertFalse(info.attemptLogin("notthepassword"));
    }

    @Test
    void adminTests() {
        // Load the Admin from persistent storage
        Admin admin = IOManager.loadAdmin("admin");

        // Test 1: getAllUsers()
        assertNotNull(admin.getAllUsers());
        assertNotNull(admin.getAllUsers());

        // Test 2: changeUserPassword()
        assertTrue(admin.changeUserPassword("mistryman", "newpassword"));
        assertNotNull(IOManager.loadStandardUser("mistryman", "newpassword"));
        admin.changeUserPassword("mistryman", "hereishispassword");
        assertNotNull(IOManager.loadStandardUser("mistryman", "hereishispassword"));

        // Test 3: changeAdminPassword()
        assertTrue(admin.changeUserPassword("admin", "newpass"));
        assertEquals(IOManager.loadAdmin("newpass").getUserInfo().getUsername(), "admin");
        assertTrue(admin.changeUserPassword("admin", "admin"));
    }

    @Test
    void filterTests() {
        List list = new List("TestList", "List for testing");
        Section def = list.getSection("Default Section");
        def.addTask("Test 1", 4, "b");
        def.addTask("Test 2", 2, "a");
        def.addTask("Test 3", 7, "aa");

        ArrayList<Task> sorted = Filter.sortBy(list, "priority");
        assertEquals(def.getTask("Test 2"), sorted.get(0));

        def.getTask("Test 1").addLabel("b");
        def.getTask("Test 2").addLabel("a");
        def.getTask("Test 3").addLabel("aa");

        sorted = Filter.sortBy(list, "label");
        assertEquals(def.getTask("Test 3"), sorted.get(1));
    }

    @Test
    void IOManagerTests() {
        // Test 1: writeSettings(), loadSettings()
        Settings settings = IOManager.loadSettings();
        Settings newSettings = new Settings();
        newSettings.initializeSettings();
        assertTrue(IOManager.writeSettings(newSettings));
        assertTrue(newSettings.equals(IOManager.loadSettings()));
        assertTrue(IOManager.writeSettings(settings));
        assertEquals(settings, IOManager.loadSettings());

        // Buildup instantiation for future tests
        UserInfo newUser = new UserInfo("spierob2", "Robbie", "Spiers", "Physics Major", "spierob2@isu.edu", "", "password");
        StandardUser user = new StandardUser(newUser);

        // Test 2: saveUserMacro(), saveUser(), loadUserMacro(), loadStandardUser()
        IOManager.saveUserMacro(newUser);
        IOManager.saveUser(user);
        assertTrue(IOManager.loadUserMacro().contains(newUser));
        assertNotNull(IOManager.loadStandardUser("spierob2", "password"));

        // Test 3: loadAdmin()
        assertNotNull(IOManager.loadAdmin("admin").getUserInfo().getUsername(), "admin");
    }
}
